name: default

on:
  push:
    branches:
      - canary

env:
  IMAGE_REPOSITORY: canary.azurecr.io/aaplss

jobs:
  main:
    environment: canary
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Registry
        uses: docker/login-action@v1 
        with:
          registry: canary.azurecr.io
          username: canary
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.IMAGE_REPOSITORY }}:latest
          build-args: |
            DATABASE_CONNECTION_STRING=${{ secrets.DATABASE_CONNECTION_STRING }}
            VAULT_URI=${{ secrets.VAULT_URI }}
            VAULT_SECRET=${{ secrets.VAULT_SECRET }}