name: default

on:
  push:
    branches: actions

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Registry
        uses: docker/login-action@v1 
        with:
          registry: mdmsua.azurecr.io
          username: mdmsua
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ass:latest,ass:${{ github.sha }}
          build-args: |
            AZURE_WEBJOBS_STORAGE=${{ secrets.AZURE_WEBJOBS_STORAGE }}
            DATABASE_CONNECTION_STRING=${{ secrets.DATABASE_CONNECTION_STRING }}