name: default

on:
  push:
    tags:
      - \d+\.\d+\.\d+

env:
  IMAGE_REPOSITORY: mdmsua.azurecr.io/aaplss

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set vars
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Registry
        uses: docker/login-action@v1 
        with:
          registry: mdmsua.azurecr.io
          username: mdmsua
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.IMAGE_REPOSITORY }}:latest,${{ env.IMAGE_REPOSITORY }}:${{ github.sha }},${{ env.IMAGE_REPOSITORY }}:${{ steps.vars.outputs.tag }}
          build-args: |
            VERSION=${{ steps.vars.outputs.tag }}
            AZURE_WEBJOBS_STORAGE=${{ secrets.AZURE_WEBJOBS_STORAGE }}
            DATABASE_CONNECTION_STRING=${{ secrets.DATABASE_CONNECTION_STRING }}
            VAULT_URI=${{ secrets.VAULT_URI }}
            VAULT_SECRET=${{ secrets.VAULT_SECRET }}