name: default

on:
  workflow_dispatch:
  push:
    tags:
      - \d+\.\d+\.\d+

env:
  IMAGE_REPOSITORY: mdmsua.azurecr.io/aaplss

jobs:
  provision:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true
      - uses: azure/powershell@v1
        if: ${{ false }}
        with:
          inlineScript: |
            Test-AzResourceGroupDeployment `
              -ResourceGroupName mdmsua `
              -TemplateFile .azure/template.json `
              -tenantId ${{ secrets.TENANT_ID }} `
              -objectId ${{ secrets.OBJECT_ID }} `
              -sqlServerSaLogin ${{ secrets.SA_USERNAME }} `
              -sqlServerSaPassword (ConvertTo-SecureString "${{ secrets.SA_PASSWORD }}" -AsPlainText) `
              -sqlServerLogin ${{ secrets.DB_USERNAME }} `
              -sqlServerPassword (ConvertTo-SecureString "${{ secrets.DB_PASSWORD }}" -AsPlainText) `
              -siteName aaplss `
              -resourceGroupNameFromTemplate mdmsua
          azPSVersion: "latest"
      - uses: azure/powershell@v1
        if: ${{ false }}
        with:
          inlineScript: |
            New-AzResourceGroupDeployment `
              -ResourceGroupName mdmsua `
              -TemplateFile .azure/template.json `
              -Name ${{ github.sha }} `
              -tenantId ${{ secrets.TENANT_ID }} `
              -objectId ${{ secrets.OBJECT_ID }} `
              -sqlServerSaLogin ${{ secrets.SA_USERNAME }} `
              -sqlServerSaPassword (ConvertTo-SecureString "${{ secrets.SA_PASSWORD }}" -AsPlainText) `
              -sqlServerLogin ${{ secrets.DB_USERNAME }} `
              -sqlServerPassword (ConvertTo-SecureString "${{ secrets.DB_PASSWORD }}" -AsPlainText) `
              -siteName aaplss `
              -resourceGroupNameFromTemplate mdmsua
          azPSVersion: "latest"

  build:
    needs: provision
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      - name: Restore tools
        run: dotnet tool restore
      - name: Restore dependencies
        run: dotnet restore
      - name: Build solution
        run: dotnet build --no-restore --configuration Release
      - name: Update database
        run: dotnet ef database update --no-build --configuration Release --project AppleSystemStatus
        env:
          DatabaseConnectionString: "Server=tcp:mdmsua.database.windows.net,1433;Initial Catalog=AppleSystemStatus;Persist Security Info=False;User ID=${{ secrets.SA_USERNAME }};Password=${{ secrets.SA_PASSWORD }};MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
          ApplicationUsername: ${{ secrets.DB_USERNAME }}
          ApplicationPassword: ${{ secrets.DB_PASSWORD }}

  deploy:
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - name: Set vars 
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - uses: actions/checkout@v2
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Registry
        uses: docker/login-action@v1
        with:
          registry: mdmsua.azurecr.io
          username: mdmsua
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.IMAGE_REPOSITORY }}:latest,${{ env.IMAGE_REPOSITORY }}:${{ github.sha }},${{ env.IMAGE_REPOSITORY }}:${{ steps.vars.outputs.tag }}
          build-args: |
            VERSION=${{ steps.vars.outputs.tag }}
            VAULT_URI=${{ secrets.VAULT_URI }}
            VAULT_SECRET=${{ secrets.VAULT_SECRET }}
