name: master

on:
  push:
    branches:
      - master

env:
  IMAGE_REPOSITORY: mdmsua.azurecr.io/aaplss

jobs:
  provision:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true
      - uses: azure/cli@v1
        with:
          inlineScript: az deployment group validate -g mdmsua -f ./.azure/main.bicep --no-prompt -p globalPrefix=mdmsua objectId=${{ secrets.OBJECT_ID }} sqlServerSaLogin=${{ secrets.SA_USERNAME }} sqlServerSaPassword=${{ secrets.SA_PASSWORD }} sqlServerLogin=${{ secrets.DB_USERNAME }} sqlServerPassword=${{ secrets.DB_PASSWORD }} siteName=aaplss

  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      - run: dotnet tool restore
      - run: dotnet restore
      - run: dotnet build --no-restore --configuration Release

  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: mdmsua.azurecr.io
          username: mdmsua
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      - uses: docker/build-push-action@v2
        with:
          push: false
          tags: ${{ env.IMAGE_REPOSITORY }}:${{ github.sha }}
